-- 0056: the Q-0059 Help-Home message (ORACLE
-- disbot/migrations/067_help_overlay_home_message.sql, imported onto the
-- 0051 help_overlay table).
--
-- Widens the help_overlay entity_kind CHECK with 'home' — exactly the
-- deliberate later migration 0051's header pre-plans — and adds bounded
-- home-only columns (NOT overloading the 100-cap presentation columns):
-- home_title (Discord embed-title cap 256), home_body (2000), home_color
-- (nullable int, 0..0xFFFFFF). One home row per guild: entity_kind='home',
-- entity_key='home'; the presentation columns stay NULL on it and the
-- overlay read model excludes 'home' rows from the hub/subsystem row set.
--
-- Absence = the byte-identical default Help Home (pinned by the golden
-- gate). An all-NULL home row is deleted by the audited write lane ("store
-- only deviations" — same contract as the presentation rows). Sole writer:
-- sb/domain/help/overlay_ops.py (help.record_set_home_message — bounds
-- enforced in the leg; these CHECKs are the backstop). Forward-only,
-- additive, idempotent.

DO $$
BEGIN
    -- 0051 declared the CHECK inline on the column, so it carries the
    -- autogenerated <table>_<column>_check name. Re-create it widened.
    ALTER TABLE help_overlay DROP CONSTRAINT IF EXISTS help_overlay_entity_kind_check;
    ALTER TABLE help_overlay
        ADD CONSTRAINT help_overlay_entity_kind_check
        CHECK (entity_kind IN ('hub', 'subsystem', 'home'));
END$$;

ALTER TABLE help_overlay ADD COLUMN IF NOT EXISTS home_title TEXT NULL;
ALTER TABLE help_overlay ADD COLUMN IF NOT EXISTS home_body  TEXT NULL;
ALTER TABLE help_overlay ADD COLUMN IF NOT EXISTS home_color INTEGER NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM   information_schema.table_constraints
        WHERE  constraint_name = 'help_overlay_home_title_check'
        AND    table_name      = 'help_overlay'
    ) THEN
        ALTER TABLE help_overlay
            ADD CONSTRAINT help_overlay_home_title_check
            CHECK (home_title IS NULL OR char_length(home_title) BETWEEN 1 AND 256);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM   information_schema.table_constraints
        WHERE  constraint_name = 'help_overlay_home_body_check'
        AND    table_name      = 'help_overlay'
    ) THEN
        ALTER TABLE help_overlay
            ADD CONSTRAINT help_overlay_home_body_check
            CHECK (home_body IS NULL OR char_length(home_body) BETWEEN 1 AND 2000);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM   information_schema.table_constraints
        WHERE  constraint_name = 'help_overlay_home_color_check'
        AND    table_name      = 'help_overlay'
    ) THEN
        ALTER TABLE help_overlay
            ADD CONSTRAINT help_overlay_home_color_check
            CHECK (home_color IS NULL OR (home_color BETWEEN 0 AND 16777215));
    END IF;
END$$;
