"""Coverage measurement — the safety-ceiling number of the rebuild.

The harness's goldens are only as protective as the fraction of the real
behavior surface they capture. This module computes that fraction against
**live, authoritative denominators** (the booted bot's own registries — never
hand-maintained lists) and names the uncovered tail explicitly.

Dimensions (each with its denominator source):

* prefix commands   — ``bot.walk_commands()``
* slash commands    — ``bot.tree.walk_commands()``
* panels (persistent) — ``core.runtime.persistent_views`` registry
* panel components  — custom_ids observed in captured component trees vs the
                      panel manifest's introspected inventory
* bus events        — ``core.events_catalogue.KNOWN_EVENTS``
* settings keys     — ``utils.settings_keys.__all__`` (via DB-delta key hits)
* DB tables         — ``pg_tables`` vs tables touched by any golden

Honesty rules: an excluded command carries a reason and counts against
coverage; the AI natural-language answer surface is measured by the separate
``tests/evals`` corpus (66 cases + 16 BTD6 probes) and is reported as a
pointer, not double-counted here.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

__all__ = ["build_coverage_report"]


def _load_goldens(goldens_root: Path) -> list[dict[str, Any]]:
    docs = []
    for path in sorted(goldens_root.glob("*/*.json")):
        docs.append(json.loads(path.read_text()))
    return docs


def _commands_covered(docs: list[dict[str, Any]]) -> set[str]:
    covered: set[str] = set()
    for doc in docs:
        for step in doc["steps"]:
            content = step["input"].get("content", "")
            if content.startswith("!"):
                covered.add(content[1:].split(" <@")[0].split(" __CHANNEL")[0])
    return covered


def _slash_covered(docs: list[dict[str, Any]]) -> set[str]:
    return {
        step["input"]["name"]
        for doc in docs
        for step in doc["steps"]
        if step["input"]["kind"] == "slash"
    }


def _custom_ids_observed(docs: list[dict[str, Any]]) -> set[str]:
    observed: set[str] = set()

    def _walk(value: Any) -> None:
        if isinstance(value, dict):
            cid = value.get("custom_id")
            if isinstance(cid, str):
                observed.add(cid)
            for v in value.values():
                _walk(v)
        elif isinstance(value, list):
            for v in value:
                _walk(v)

    for doc in docs:
        _walk(doc)
    return observed


def _events_observed(docs: list[dict[str, Any]]) -> set[str]:
    return {
        event["event"]
        for doc in docs
        for step in doc["steps"]
        for event in step.get("events", [])
    }


def _tables_touched(docs: list[dict[str, Any]]) -> set[str]:
    return {table for doc in docs for table in doc.get("db_delta", {})}


def _match_command(qname: str, covered: set[str]) -> bool:
    if qname in covered:
        return True
    # covered strings may carry synthesized args: "warn 3" etc.
    return any(c == qname or c.startswith(qname + " ") for c in covered)


async def build_coverage_report(goldens_root: Path) -> str:
    from parity.harness.boot import Harness

    harness = await Harness.start()
    bot = harness.bot
    docs = _load_goldens(goldens_root)
    skips_path = goldens_root / "_sweep_skips.json"
    skipped: dict[str, str] = (
        json.loads(skips_path.read_text()) if skips_path.exists() else {}
    )

    lines: list[str] = []
    lines.append("# Golden harness coverage — the rebuild's safety ceiling")
    lines.append("")
    lines.append(
        "> GENERATED by `python3.10 -m parity.run coverage` — do not edit. "
        "Denominators come from the booted bot's own registries.",
    )
    lines.append("")
    lines.append(f"Golden corpus: **{len(docs)} cases** under `parity/goldens/`.")
    lines.append("")

    summary_rows: list[tuple[str, int, int, float]] = []

    # ---------------------------------------------------------------- prefix
    # hidden commands are dispatchable behavior — they count in the
    # denominator like any other surface (hidden only affects help listings)
    covered_cmds = _commands_covered(docs)
    all_prefix = sorted(c.qualified_name for c in bot.walk_commands())
    got = [q for q in all_prefix if _match_command(q, covered_cmds)]
    missing_prefix = [q for q in all_prefix if not _match_command(q, covered_cmds)]
    summary_rows.append(
        ("Prefix commands", len(got), len(all_prefix), len(got) / len(all_prefix)),
    )

    # ----------------------------------------------------------------- slash
    slash_covered = _slash_covered(docs)
    import discord

    all_slash = sorted(
        c.qualified_name
        for c in bot.tree.walk_commands()
        if isinstance(c, discord.app_commands.Command)
    )
    slash_got = [q for q in all_slash if q in slash_covered]
    missing_slash = [q for q in all_slash if q not in slash_covered]
    summary_rows.append(
        (
            "Slash commands",
            len(slash_got),
            len(all_slash),
            len(slash_got) / max(len(all_slash), 1),
        ),
    )

    # ---------------------------------------------------------------- panels
    from core.runtime.persistent_views import iter_registered_view_classes

    persistent_classes = [cls.__name__ for cls in iter_registered_view_classes()]
    observed_cids = _custom_ids_observed(docs)
    from core.runtime.panel_manifest import build_panel_manifest

    manifest = build_panel_manifest()
    manifest_ids: set[str] = set()
    panels_with_hit: set[str] = set()
    for entry in manifest.panels:
        ids = {b.custom_id for b in entry.buttons if b.custom_id}
        manifest_ids.update(ids)
        if ids & observed_cids:
            panels_with_hit.add(entry.subsystem)
    static_got = sorted(manifest_ids & observed_cids)
    static_missing = sorted(manifest_ids - observed_cids)
    summary_rows.append(
        (
            "Persistent-panel components (custom_ids)",
            len(static_got),
            len(manifest_ids),
            len(static_got) / max(len(manifest_ids), 1),
        ),
    )
    summary_rows.append(
        (
            "Persistent panels (≥1 component captured)",
            len(panels_with_hit),
            len(persistent_classes),
            len(panels_with_hit) / max(len(persistent_classes), 1),
        ),
    )

    # ---------------------------------------------------------------- events
    from core.events_catalogue import KNOWN_EVENTS

    observed_events = _events_observed(docs)
    events_got = sorted(observed_events & KNOWN_EVENTS)
    events_missing = sorted(KNOWN_EVENTS - observed_events)
    summary_rows.append(
        (
            "Bus events",
            len(events_got),
            len(KNOWN_EVENTS),
            len(events_got) / len(KNOWN_EVENTS),
        ),
    )

    # ---------------------------------------------------------------- tables
    from utils.db import pool

    all_tables = sorted(
        r["tablename"]
        for r in await pool.fetchall(
            "SELECT tablename FROM pg_tables WHERE schemaname='public'",
        )
        if r["tablename"] != "schema_migrations"
    )
    touched = _tables_touched(docs)
    tables_got = [t for t in all_tables if t in touched]
    tables_missing = [t for t in all_tables if t not in touched]
    summary_rows.append(
        (
            "DB tables (touched by ≥1 golden)",
            len(tables_got),
            len(all_tables),
            len(tables_got) / len(all_tables),
        ),
    )

    # --------------------------------------------------------------- settings
    import utils.settings_keys as settings_keys_mod

    key_names = list(getattr(settings_keys_mod, "__all__", []))
    key_values: set[str] = set()
    for name in key_names:
        value = getattr(settings_keys_mod, name, None)
        if isinstance(value, str):
            key_values.add(value)
    touched_keys: set[str] = set()
    for doc in docs:
        for table, delta in doc.get("db_delta", {}).items():
            if table not in ("settings", "guild_settings", "global_settings"):
                continue
            for row in delta.get("added", []) + delta.get("removed", []):
                for column in ("key", "setting_key", "name"):
                    v = row.get(column)
                    if isinstance(v, str):
                        touched_keys.add(v)
    keys_got = sorted(key_values & touched_keys)
    summary_rows.append(
        (
            "Settings keys (mutated by ≥1 golden)",
            len(keys_got),
            len(key_values),
            len(keys_got) / max(len(key_values), 1),
        ),
    )

    # --------------------------------------------------------------- summary
    lines.append("## Summary")
    lines.append("")
    lines.append("| Surface | Captured | Total | Coverage |")
    lines.append("|---|---|---|---|")
    for label, got_n, total, frac in summary_rows:
        lines.append(f"| {label} | {got_n} | {total} | **{frac:.0%}** |")
    lines.append("")
    lines.append(
        "The **AI natural-language answer surface** is covered by the "
        "existing black-box eval corpus (`tests/evals/`: 66 golden cases + "
        "16 BTD6 grounding probes + the CI smoke matrix) — reported here as "
        "a sibling asset, not double-counted.",
    )
    lines.append("")

    # ------------------------------------------------------------ methodology
    lines.append("## Methodology")
    lines.append("")
    lines.append(
        "- **Denominators are live**: command lists from `bot.walk_commands()`"
        " / `bot.tree.walk_commands()` on the booted bot; panel components"
        " from `core.runtime.panel_manifest.build_panel_manifest()`; events"
        " from `KNOWN_EVENTS`; tables from `pg_tables`.",
    )
    lines.append(
        "- **Captured** means: at least one golden drives the surface"
        " (command invoked, custom_id rendered in a captured component tree,"
        " event observed on the bus tap, table appearing in a DB delta).",
    )
    lines.append(
        "- **Coverage is breadth, not depth**: one captured invocation per"
        " command (admin persona, synthesized args) plus curated multi-step"
        " flows. A command with rich flag/subpath behavior counts as covered"
        " after one path — the per-subsystem coverage notes required at every"
        " `pending → ported` flip (design spec §10.1) are where depth gets"
        " audited.",
    )
    lines.append(
        "- **Usage weighting is not applied**: the production usage counter"
        " (`command_total{cog,command,result}`) is an in-process Prometheus"
        " metric; no historical scrape exists in this environment. Weighted"
        " coverage needs the Phase-0.5 telemetry sidecar (design spec"
        " §2.10.4) — flagged as follow-up, not silently faked.",
    )
    lines.append("")

    # --------------------------------------------------------- uncovered tail
    lines.append("## The uncovered tail — named explicitly")
    lines.append("")
    lines.append(f"### Prefix commands not captured ({len(missing_prefix)})")
    lines.append("")
    if missing_prefix:
        for name in missing_prefix:
            reason = skipped.get(name, "no golden drives it yet")
            lines.append(f"- `{name}` — {reason}")
    else:
        lines.append("*(none)*")
    lines.append("")
    if missing_slash:
        lines.append(f"### Slash commands not captured ({len(missing_slash)})")
        lines.append("")
        for name in missing_slash:
            reason = skipped.get(f"/{name}", "no golden drives it yet")
            lines.append(f"- `/{name}` — {reason}")
        lines.append("")
    lines.append(
        f"### Persistent-panel custom_ids never rendered ({len(static_missing)})",
    )
    lines.append("")
    lines.append(
        ", ".join(f"`{c}`" for c in static_missing) if static_missing else "*(none)*",
    )
    lines.append("")
    lines.append(f"### Catalogued events never observed ({len(events_missing)})")
    lines.append("")
    lines.append(
        ", ".join(f"`{e}`" for e in events_missing) if events_missing else "*(none)*",
    )
    lines.append("")
    lines.append(f"### Tables never touched by a golden ({len(tables_missing)})")
    lines.append("")
    lines.append(
        ", ".join(f"`{t}`" for t in tables_missing) if tables_missing else "*(none)*",
    )
    lines.append("")

    await harness.close()
    return "\n".join(lines) + "\n"
